M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Mon 31 Oct 2022 03:29:01 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-31T15:29:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C14.000
%
G90
G05
T1
X35.585Y21.831
X35.585Y0.831
X66.585Y21.831
X66.585Y0.831
T2
X65.835Y10.081
T3
X31.025Y17.046
X31.787Y-70.076
T4
X28.181Y-15.872
T0
M30
