{
 "title": "SOASENSE devices",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensor_id",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"ppz-data-bucket\",\n    tag: \"sensor_id\",\n    measurement: \"mqtt_consumer\",\n)\n\n"
   }
  ]
 },
 "panels": [
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Counter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"counter\")\n  |> aggregateWindow(every: 120s, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Main firmware version",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"fw_version\")\n  \n  "
    }
   ]
  },
  {
   "title": "OPC-N3 Firmware version",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"opcn3_fw_ver\")\n  \n  "
    }
   ]
  },
  {
   "title": "OPC-N3 Serial number",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"opcn3_fw_ver\")\n  \n  "
    }
   ]
  },
  {
   "title": "SPS-30 Firmware version",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"sps30_fw_ver\")\n  \n  "
    }
   ]
  },
  {
   "title": "SPS-30 Serial number",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"sps30_fw_ver\")\n  \n  "
    }
   ]
  },
  { "title": "OPC-N3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Particles [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"opcn3_PM1\" or r._field == \"opcn3_PM2_5\" or r._field == \"opcn3_PM10\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  {
   "title": "Particles [counts]",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"opcn3_bin0\" or r._field == \"opcn3_bin1\" or r._field == \"opcn3_bin2\" or r._field == \"opcn3_bin3\" or r._field == \"opcn3_bin4\" or r._field == \"opcn3_bin5\" or r._field == \"opcn3_bin6\" or r._field == \"opcn3_bin7\" or r._field == \"opcn3_bin8\" or r._field == \"opcn3_bin9\" or r._field == \"opcn3_bin10\" or r._field == \"opcn3_bin11\" or r._field == \"opcn3_bin12\" or r._field == \"opcn3_bin13\" or r._field == \"opcn3_bin14\" or r._field == \"opcn3_bin15\" or r._field == \"opcn3_bin16\" or r._field == \"opcn3_bin17\" or r._field == \"opcn3_bin18\" or r._field == \"opcn3_bin19\" or r._field == \"opcn3_bin20\" or r._field == \"opcn3_bin21\" or r._field == \"opcn3_bin22\" or r._field == \"opcn3_bin23\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  { "title": "SPS30", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "SPS30 [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"sps30_PM1\" or r._field == \"sps30_PM2\" or r._field == \"sps30_PM10\" or r._field == \"sps30_PM4\")\n  |> aggregateWindow(every: 120s, fn: mean)\n  "
    }
   ]
  },
  {
   "title": "SPS30 [ug/m3]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "query": "\nfrom(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"sps30_NumPM0\" or r._field == \"sps30_NumPM1\" or r._field == \"sps30_NumPM2\" or r._field == \"sps30_NumPM4\" or r._field == \"sps30_NumPM10\")\n  |> aggregateWindow(every: 120s, fn: mean) "
    }
   ]
  },
  { "title": "Gas sockets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Socket 1",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_1_1\" or r._field == \"AD_socket_1_2\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  {
   "title": "Socket 2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_2_1\" or r._field == \"AD_socket_2_2\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  {
   "title": "Socket 3",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_3_1\" or r._field == \"AD_socket_3_2\")\n  |> aggregateWindow(every: 120s, fn: mean)\n"
    }
   ]
  },
  {
   "title": "Socket 4",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"AD_socket_4_1\" or r._field == \"AD_socket_4_2\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  { "title": "Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_t\" or r._field == \"opcn3_t\" )\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_h\" or r._field == \"opcn3_h\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"ppz-data-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mqtt_consumer\")\n  |> filter(fn: (r) => r.sensor_id == \"${sensor_id}\")\n  |> filter(fn: (r) => r._field == \"bme280_p\")\n  |> aggregateWindow(every: 120s, fn: mean)"
    }
   ]
  }
 ]
}